### ISSUE TITLE
Amazing but too opinionated about page style

### ISSUE THREAD

**Issue by frederikhors** [matyunya/smelte#37]
This project is truly awesome!

I wanna use it with an existing project but your `tailwind.config.js` and `tailwind.css` are just too opinionated, example:

```css
html {
  font-family: "Roboto", sans-serif;
}
```

Is there a way I can use your components without your page style?

It would be amazing if each component can bring it's style together and just that.

What do you think about?
